---
- name: Setup system
  ansible.builtin.include_tasks:
    file: setup.yml
    apply:
      tags:
        - setup
  tags:
    - always

- name: Setup nvidia
  ansible.builtin.include_tasks:
    file: nvidia.yml
    apply:
      tags:
        - nvidia
  tags:
    - always

- name: Setup coral
  ansible.builtin.include_tasks:
    file: coral.yml
    apply:
      tags:
        - coral
  tags:
    - always

- name: Setup backup
  ansible.builtin.include_tasks:
    file: backup.yml
    apply:
      tags:
        - backup
  tags:
    - always

- name: Setup frigate
  ansible.builtin.include_tasks:
    file: frigate.yml
    apply:
      tags:
        - frigate
  tags:
    - always
